### ISSUE TITLE
Android app is supported by 0 devices

### ISSUE THREAD

**Issue by Dankospark-team** [zynkware/Document-Scanning-Android-SDK#4]
Hi

Thanks for the Awesome work on this and making this available. 

When publishing to the Play store, 0 Devices are available. 

I suspect that this permission:

<uses-feature android:name="android.hardware.camera2"  /> needs the android:required="false" flag as per this post:
https://stackoverflow.com/questions/14020237/android-app-is-supported-by-0-devices

Could you possibly look into this?

Kind Regards,
Henno Bakker

**Comment by Dankospark-team** [comment]
@iulian-buzila

**Comment by de0phantom** [comment]
@iulian-buzila , I agree with @Dankospark-team .  Had the same issue.  The moment I removed library the supported devices bounced to 9k+ as expected.  My assessment is "camera2" usage in the manifest is causing this issue.  Another stack-overflow link (if it helps :)

https://stackoverflow.com/questions/52760131/my-app-compatible-with-0-devices-android

**Comment by Dankospark-team** [comment]
Can confirm that this is the issue. In the end I just added the  project as a module and published to Playstore with success.

**Comment by jayashankar** [comment]
Same issue still exists.

**Comment by fukemy** [comment]
big problem, any solution?

**Comment by Piidro** [comment]
I bumped into this issue as well. Any solutions from anyone?

**Comment by sujay-appringer** [comment]
I had the same issue. I fixed it by overriding the camera feature in my manifest.
`<uses-feature
        android:name="android.hardware.camera2"
        android:required="false"
        tools:replace="required"/>`

**Comment by iulian-buzila** [comment]
Sorry for late response.
You guys can try a new version 1.1.1 if still use this library
https://github.com/zynkware/Document-Scanning-Android-SDK/commit/74a10c9c7859f7ab324a93c53ea21d93fc363117

**Comment by fukemy** [comment]
too late for 2 years, I have some forum + skype communites then I warn them to avoid this lib
